### ISSUE TITLE
Where and how are you hosting this? 

### ISSUE THREAD

**Issue by GitHubEmploy** [bchiang7/bchiang7.github.io#16]
Hey, wondering how you are hosting this I would love to use it. I would prefer a detailed explanation but a short paragraph would be fine as well.

**Comment by jayavardhan3112** [comment]
Hi, @GitHubEmploy any response on this ? even I am confused about how to deploy this

**Comment by bchiang7** [comment]
There are many ways to deploy Jekyll static sites. See Jekyll's [deployment documentation](https://jekyllrb.com/docs/deployment/). I used GitHub pages, but you can also use other popular services like Netlify or Vercel.

**Comment by shamonhashmi148** [comment]
yes you can deploy it in many other popular services also
