### ISSUE TITLE
Migrate to gulp 4

### ISSUE THREAD

**Issue by bchiang7** [bchiang7/bchiang7.github.io#5]
Migrating gulp from 3.9.1 to 4.0 will resolve some of the dependency vulnerabilities pointed out by running `npm audit`.

Gulp 4.0: https://github.com/gulpjs/gulp/tree/4.0
Docs: https://github.com/gulpjs/gulp/blob/4.0/docs/API.md

**Comment by mayeedwin** [comment]
Awesome. Great work @bchiang7

**Comment by robincsamuel** [comment]
@bchiang7 

I used your repo to build my site and I migrated to gulp 4. You can see the commit [here](https://github.com/robincsamuel/robincsamuel.github.io/commit/815abbea592dec0cc2a554587bc3596ed8facf28).

I can raise a PR if that looks good.

Thanks for the theme :-)

**Comment by bchiang7** [comment]
@robincsamuel a PR would be great!

**Comment by robincsamuel** [comment]
@bchiang7 #10 

#8 is also solved, will work with the latest version of Node.js.

**Comment by bchiang7** [comment]
@robincsamuel Thanks for your contribution!! Closing via #10
