### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by vs74** [bchiang7/bchiang7.github.io#8]
Hi, 
I forked your branch and tried following the instructions as given in `Readme.md`. Everything except `step 3 npm start ` works fine. I am attaching the screenshot of the error which I encountered. Any help would be greatly appreciated. 
<img width="1003" alt="Screenshot 2020-01-04 at 3 41 55 PM" src="https://user-images.githubusercontent.com/31419210/71767111-ce8fdd00-2f08-11ea-806a-13caf2d49758.png">

**Comment by bchiang7** [comment]
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

Try downgrading your version of node? I think I was on node 9 or 10 when I was working on this project

**Comment by vs74** [comment]
That works, thank you so much.
